server:
  shutdown: graceful

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

telegram:
  bot:
    username: test
    token: test_token

logging:
  level:
    org:
      springframework:
        cache: debug
