version: "3.8"
services:
  db:
    container_name: database
    image: "postgres:16.1-alpine3.19"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"